## NumPy

###### NumPy (numerical Python) is an open source python library that aids in mathematical, scientific, engineering, and data science programming.

###### NumPy is the fundamental package for scientific computing with Python. it contains:
###### *.a powerful N-dimental array object
###### *.extension package to python for multi-dimentional arrays
###### *.designed for scientific computation -- liner algebra, fourier transform, and ran dom number capilities.
###### *.Numpy can also be used as an efficient multi-dimensional container of generic data.
###### *.this allows Numpy to seamlessly and speedily integrate with a wide variety of databases.
###### *.numpy is an incredible library to perform mathematical and statistical operations because it is fast and memory. efficient.closer to hardware (efficiency)

In [2]:
### load in Numpy (Import Numpy package)
import numpy as np

### Ndarray Object

###### The most important object defined in Numpy is an N-dimensional array type called ndarray.it describes the collection of items of the same type.item in the collection can be accessed using a zero-based index.Each element in ndarray ia an object of data-type object (called dtype).

###### The basic ndarray is created using an array function inNumpy as follows:
###### numpy.array(object, dtype = None)

##### NOTE: in Numpy,axis = 0 is cols and axis = 1 is rows.

In [1]:
i=[9,3,5,6]

In [2]:
print(i)

[9, 3, 5, 6]


In [3]:
print(type(i))

<class 'list'>


In [12]:
A=np.array(i)

In [13]:
print(A)

[9 3 5 6]


In [14]:
print(type(A))

<class 'numpy.ndarray'>


###### Why it is useful: Memory-efficient container that provides fast numerical operations.

In [15]:
# python list
l=range(1000)
%timeit [i**2 for i in l]

120 µs ± 5.22 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [16]:
m=np.arange(1000)
%timeit m**2

1.88 µs ± 30.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


##### Creating arrays (Manually creating arrays)

In [17]:
# 1-D
j=np.array([6,3,1,8])
j

array([6, 3, 1, 8])

In [18]:
# print dimensions
j.ndim

1

In [19]:
# Shape
j.shape

(4,)

In [20]:
# 2-D
k=np.array ([[2,5,3], [9,6,1]])
k

array([[2, 5, 3],
       [9, 6, 1]])

In [21]:
k.ndim

2

In [22]:
k.shape

(2, 3)

In [23]:
# 3-D
n=np.array([[[2,4], [5,1]], [[3,8], [9,3]]])
n

array([[[2, 4],
        [5, 1]],

       [[3, 8],
        [9, 3]]])

In [24]:
n.ndim

3

In [25]:
n.shape

(2, 2, 2)

##### Creating NumPy Arrays From a List

In [26]:
# We know how to create a list,right
list=[3,6,2]
list

[3, 6, 2]

In [27]:
np.array(list)

array([3, 6, 2])

In [29]:
# We can convert a matrix which is also a list to array
matrix=[[3,5,2],[6,1,8],[9,3,6]]
matrix

[[3, 5, 2], [6, 1, 8], [9, 3, 6]]

In [30]:
np.array(matrix)

array([[3, 5, 2],
       [6, 1, 8],
       [9, 3, 6]])

In [32]:
np.array(matrix).shape

(3, 3)

#### Functions of creating arrays
##### A new ndarray object can be created by any of the following array creation routines:
###### .list_nparray = np.array(pytjon_list,dtype)
###### .arange_array = np.arange(start,end,step,dtype)
###### .zero_array =np.zeros(shape,dtype)
###### .ones_array = np.ones(shape,dtype)
###### .linspace_array = np.linspace(start_element,end_element,num_of_elements)
###### .empty_array = np.empty(shape,dtype)
###### .random_array= np.random.randint(start,end,num_elements)

##### arange
###### . Which will Return evenly spaced values within a given interval.

In [3]:
# using arrange function -->arrange is an array-valued vrsion of the built-in pyton range function
e = np.arange(10) # 0....n-1
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = np.arange(1,10,2) # start, end (exclusive),step
f

array([1, 3, 5, 7, 9])

##### Linespace
###### .Return evenly spaced numbers over a specified interval.

In [6]:
# using Linspace
g = np.linspace(0,5,6) # start,end,number of points
g

array([0., 1., 2., 3., 4., 5.])

In [7]:
# I want to get 3 evenly spaced points between 0 to 10
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

##### zeros and ones
###### .Generate arrays of zeros or ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
h=np.zeros((2,2))
h

array([[0., 0.],
       [0., 0.]])

In [10]:
h=np.ones((4,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### eye-->Creates an identify matrix
###### . An identify matrix if you are not familier is used in linear algebra problem and is a two dimentional squared matrix mens number of rows are samwe as columns with diagonals of ones and everything is zero.

In [3]:
c = np.eye(3) #Return a 2-D array eith ones on the diagonal and zeros elsewhere.
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
d = np.eye(3,2) #3 is number of rows, 2 is numberof columns, index of diagonal start with 0
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [5]:
# Create array using diag function
a = np.diag([5,3,8,2])
a

array([[5, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 2]])

In [6]:
np.diag(a)

array([5, 3, 8, 2])

###### Random -->NumPy also has lots of ways to create random number arrays:

In [7]:
#randint -- return random integers from start (inclusive) to end (exclusive).
random_array = np.random.randint(1,100,7)
print(random_array)

[36 36  4 39 95 44 75]


In [8]:
#rand -- create an array of the given shape and populate it with random sample s from a uniform distribution over [0,1].
a = np.random.rand(5)
a

array([0.9916435 , 0.09983143, 0.0168997 , 0.2803746 , 0.90070175])

In [9]:
#randn -- return a sample (or sample) from the "standard  normal" distribution. **gausian**
a = np.random.randn(20)
a

array([-0.95513321, -0.10347411,  0.19837371, -0.83596215, -1.03567005,
        0.93757139, -1.94058187,  0.10028406, -0.21880483, -0.30318555,
       -0.33568526,  0.50261723,  0.12797172, -2.09906434,  0.25588121,
       -3.48469575, -1.3339548 ,  0.43586241,  1.38811039,  2.70867199])

### Copy array

In [10]:
a = np.array([4,9,2])
b = a
b[0]=6
print(a)
print(b)

[6 9 2]
[6 9 2]


### Reshape array

In [13]:
arr = np.arange(16)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)


In [14]:
# Notice the two sets of brackets
a1 = arr.reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a = np.array([[5,3,1],[7,9,2]])
print(a)
print('shape of a:{}'.format(a.shape))

[[5 3 1]
 [7 9 2]]
shape of a:(2, 3)


In [16]:
# reshaping 
b = a.reshape(3,2)
print(b)
print('shape of b:{}'.format(b.shape))

[[5 3]
 [1 7]
 [9 2]]
shape of b:(3, 2)


### Transpose array

In [17]:
a = np.array([[5,3,1],[7,9,2]])
print('shape:{}'.format(a.shape))
print(a)

shape:(2, 3)
[[5 3 1]
 [7 9 2]]


In [19]:
b=a.T
print(b)

[[5 7]
 [3 9]
 [1 2]]


In [20]:
a = np.array([[5,3,1],[7,9,2]])
a.ravel() #Return a contigious flattened array.A 1-D array, containing the element of the input, is returned. A copy is made only if needed.

array([5, 3, 1, 7, 9, 2])

In [22]:
b.ravel()

array([5, 7, 3, 9, 1, 2])

### Sorting

In [23]:
# Sorting along an axis:
# axis=1 --> row and axis=0 --> column
a = np.array([[4,2,1],[9,3,7]])
b = np.sort(a, axis=1)
b

array([[1, 2, 4],
       [3, 7, 9]])

### Add/Remove operation on a numpy array

In [29]:
a = np.array([5,7,2])
a = np.append(a,[6,8,1])
print('NumPy array after addition:',a)

NumPy array after addition: [5 7 2 6 8 1]


In [30]:
a = np.delete(a,2)
print('NumPy array after deletion of one element:',a)

NumPy array after deletion of one element: [5 7 6 8 1]


### Indexing

###### The items of an array can be accessed and assigned to the same way as other Python sequencees(e.g lists):

In [31]:
a = np.arange(2,9)
print(a)
print(a[4])

[2 3 4 5 6 7 8]
6


In [35]:
# For multidimentional arrays, indexes are tuples of integers:
a = np.diag([5,8,2])
print(a)
print(a[2,1])

[[5 0 0]
 [0 8 0]
 [0 0 2]]
0


In [36]:
a[2,1] = 4 # Assigning value
a

array([[5, 0, 0],
       [0, 8, 0],
       [0, 4, 2]])

### Slicing

In [38]:
a = np.arange(5,20)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
a[2:12:3] # [startindex: endindex(exclusive) : step]

array([ 7, 10, 13, 16])

In [40]:
# We can also can combine assignment and slicing:
a = np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [42]:
a[5:] = 7
a

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 7])

In [43]:
b= np.arange(5)
b

array([0, 1, 2, 3, 4])

In [44]:
b[::-1]

array([4, 3, 2, 1, 0])

In [45]:
a[5:] = b [::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#### Fancy indexing
###### Numpy arrays can be indexed with slices,but also with boolean or intrger arrays (Masks). this method is called fancy indexing.it creates copies not views.

In [49]:
a = np.random.randint(0,20,5)
a

array([14, 13,  0, 11, 11])

In [50]:
a[a%2==0]

array([14,  0])

In [51]:
a[a%2==0] = -1
a

array([-1, 13, -1, 11, 11])

##### Indexing with an array of integers

##### This is the matrix multiplication

In [52]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2,5,1,4,6]]

array([20, 50, 10, 40, 60])

In [55]:
# New values can be assigned
a[[6,2]]=-22
a

array([  0,  10, -22,  30,  40,  50, -22,  70,  80,  90])

### Operations

###### 1.Basic Operations
###### with scalars

In [56]:
a = np.array([4,6,9,2]) # create an array
print(a)
print(a+1)

[4 6 9 2]
[ 5  7 10  3]


In [57]:
a ** 2

array([16, 36, 81,  4])

###### All arithmetic operates elementwise

In [59]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [60]:
a - b

array([2., 4., 7., 0.])

In [61]:
a * b

array([ 8., 12., 18.,  4.])

In [62]:
a = np.array([[3,2],[5,6],[9,1]])
b = np.array([[3,3],[3,3],[3,3]])

# adding a and b
print('sum of a and b:\n',a+b)

sum of a and b:
 [[ 6  5]
 [ 8  9]
 [12  4]]


In [63]:
# multiply a and b - elementwise multiplication
print('product of and b :\n',a * b )

product of and b :
 [[ 9  6]
 [15 18]
 [27  3]]


In [64]:
# array multiplication
c = np.diag([4,2,7,4])
print(c * c)

[[16  0  0  0]
 [ 0  4  0  0]
 [ 0  0 49  0]
 [ 0  0  0 16]]


In [65]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print('matrix multipication:\n',np.matmul(b,a))

matrix multipication:
 [[21 30 21]
 [26 36 26]
 [31 42 31]]


In [66]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print('matrix multipication:\n',np.matmul(a,b))

matrix multipication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [27]:
a=np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,6],[3,2],[8,5]])
print('matrix multipication:\n',np.matmul(a,b))

matrix multipication:
 [[18 15]
 [48 41]
 [78 67]]


##### This is the array multiplication

In [6]:
A=np.array([[2,1],[3,4],[6,2]])
B=np.array([[3,1],[6,2],[4,3]])
print(A * B)

[[ 6  1]
 [18  8]
 [24  6]]


In [7]:
A=np.array([[2,1],[3,4],[6,2]])
B=np.array([[3,1],[6,2],[4,3]])
print(B * A)

[[ 6  1]
 [18  8]
 [24  6]]


##### comparision

In [67]:
a = np.array([4,2,8,9])
b = np.array([2,6,3,9])
a == b

array([False, False, False,  True])

In [68]:
a > b

array([ True, False,  True, False])

In [69]:
# array-wise comparisions
a = np.array([3,6,2,1])
b = np.array([8,2,9,6])
c = np.array([3,6,2,1])

In [70]:
np.array_equal(a,b)

False

In [71]:
np.array_equal(a,c)

True

###### Logical Operations

In [8]:
x=np.array([1,1,0,0], dtype=bool)
y=np.array([1,0,1,0], dtype=bool)

np.logical_or(x,y)

array([ True,  True,  True, False])

In [9]:
np.logical_and(x,y)

array([ True, False, False, False])

In [11]:
x=np.array([1,1,0,0])
y=np.array([1,0,1,0])

np.logical_or(x,y)

array([ True,  True,  True, False])

In [12]:
np.logical_and(x,y)

array([ True, False, False, False])

In [18]:
x=np.array([2.3,1.4,6.2], dtype=int)
y=np.array([7.2,9.3,5.1], dtype=int)
x+y
# np.logical_or(x,y)

array([ 9, 10, 11])

In [16]:
x+y

array([2, 1, 1, 0])

In [22]:
x=np.array([1,1,0,0], dtype=float)
y=np.array([1,0,1,0], dtype=float)
x+y
# np.logical_or(x,y)

array([2., 1., 1., 0.])

##### Transcendental function

##### Basic Reduction

In [33]:
i=np.array([[1,2],[3,4,]])
i.sum()

10

###### Transcendental Functions:

In [72]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [73]:
np.log(a)

C:\Users\RamaB\AppData\Local\Temp\ipykernel_7772\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [74]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

###### Shape Mismatch

In [75]:
a = np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Basic Reductions

###### Computing Sums

In [76]:
x = np.array([3,6,9,1])
np.sum(x)

19

In [77]:
# sum by rows and by columns
x = np.array([[3,3],[5,5]])
x

array([[3, 3],
       [5, 5]])

In [78]:
#columns first dimension
x.sum(axis=0) 

array([8, 8])

In [79]:
#rows second dimension
x.sum(axis=1) 

array([ 6, 10])

###### Other Reductions

In [80]:
x = np.array([3,6,2])
x.min()

2

In [81]:
x.max()

6

In [82]:
# Index of minimum element
x.argmin()

2

In [83]:
# Index of maximum ele,ent
x.argmax()

1

#### Statistics

In [84]:
normal_array = np.arange(0,15,1)
print('array is:-',format(normal_array))

### Min
print('min element is:-',np.min(normal_array))

### Max
print('max element is:-',np.max(normal_array))

### Sum
print('Sum of elements in array is:-',np.sum(normal_array))

### Mean
print('mean of elements in array is :-',np.mean(normal_array))

### Median
print('median of elements inarray is :-',np.median(normal_array))

### Sd
print('Standard deviation of elements in array is :-',np.std(normal_array))

array is:- [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
min element is:- 0
max element is:- 14
Sum of elements in array is:- 105
mean of elements in array is :- 7.0
median of elements inarray is :- 7.0
Standard deviation of elements in array is :- 4.320493798938574
